# Generated by Django 2.2.6 on 2019-10-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persekot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='no_hp',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='no_hape',
            field=models.CharField(default='123456789012', max_length=12),
            preserve_default=False,
        ),
    ]
