# Generated by Django 2.2.6 on 2019-11-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persekot', '0002_auto_20191031_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persekot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('tgl_pk', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='karyawan',
            name='unit_kerja',
            field=models.IntegerField(choices=[(1, 'Kepesertaan'), (2, 'Pelayanan'), (3, 'Keuangan'), (4, 'Umum & SDM')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PetanggungJawabanPersekot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_selesai_pk', models.DateField()),
                ('persekot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persekot.Persekot')),
            ],
        ),
        migrations.AddField(
            model_name='persekot',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persekot.Karyawan'),
        ),
    ]
