# Generated by Django 2.2.6 on 2019-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persekot', '0003_auto_20191115_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
